#ifndef BFE_ERR_CODES_H
#define BFE_ERR_CODES_H

#define BFE_SUCCESS	0
#define BFE_ERR_GENERAL 1
#define BFE_ERR_INVALID_PARAM 2
#define BFE_ERR_KEY_PUNCTURED 3
#define BFE_ERR_NO_MORE_TIME_INTERVALS 4

#endif //BFE_ERR_CODES_H
